### ISSUE TITLE
서버에서 ip 폴더 만들어서 안에 넣는게 잘 안됩니다..

### ISSUE THREAD

**Issue by hansoi** [youFrivolous/sw-project#27]
지금 저희 구조가 ip를 치고, 디렉토리나 파일명을 치면 가지잖아요 ㅠㅠ 근데 지금 하려는게
ip를 치면 ip 폴더를 만들고 그 안에 디렉토리랑 파일을 집어 넣는건데
상대경로를 절대경로로 바꾸는 과정에서 ip 폴더를 만들어서  안에 넣는게.. 6시간째 하고 있는데
생각 보다 너무 복잡하네욤 ㅠ 첨부터 저희가 ip폴더를 만들려고 한게 아니라..

다른 방향으로 바꿔서 생각했으면 좋겠는데 어떠신가요?

**Comment by joonas-yoon** [comment]
(오프라인 회의에서 결정된 내용입니다.)
변경 내용:
- ip별 디렉토리를 생성하는 것이 아닌, 파일명에 ip와 디렉토리 정보를 표현하기로 변경
