### ISSUE TITLE
C언어에서 mysql 연동

### ISSUE THREAD

**Issue by rlaroanf** [youFrivolous/sw-project#28]
db를 이용해 이미지를 올리는 작업을 합니다.

**Comment by joonas-yoon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DB 연동](https://trello.com/c/hpAxQD9w/41-db-%EC%97%B0%EB%8F%99)

**Comment by rlaroanf** [comment]
http://potatoggg.tistory.com/62

**Comment by joonas-yoon** [comment]
pull-request는 없나요?
