### ISSUE TITLE
파일명에 적히는 IP가 잘못 됨

### ISSUE THREAD

**Issue by joonas-yoon** [youFrivolous/sw-project#32]
확인해본 결과, 파일명에 적히는 IP가 클라이언트가 아닌 서버의 IP네요.

#29 에서 작성된 코드 일부를 수정하면 해결될 것 같습니다.

**Comment by hansoi** [comment]
아 ㅠㅠ 마지막에 확인하는 과장에서 실수가 .. 넵 ㅜㅜ
