### ISSUE TITLE
같은 ip내에서 udp 송수신 완료했는데 다른 ip에서 보내질까

### ISSUE THREAD

**Issue by rlaroanf** [youFrivolous/sw-project#4]
http://forum.falinux.com/zbxe/index.php?mid=network_programming&document_srl=406058

여기 개꿀

**Comment by joonas-yoon** [comment]
이거 제꺼 샘플로도 해봤는데 동방에 34 고정 IP로 시도해봤는데 안되더라구요. 다른 고정 IP 몇개로 더 테스트가 필요해보입니다.

**Comment by joonas-yoon** [comment]
같은 공유기 내에서 서로 다른 ip의 파일 전송은 확인했습니다. 완전히 다른 ip주소가 필요해요.

**Comment by joonas-yoon** [comment]
https://github.com/youFrivolous/sw-project/commit/1b96a5aa99bf66814337b40d774bfb6ff77cea79 에서 확인한 결과 성공.
